Set the correct home directory on the dockerized users
I don't remember the exact details. A yocto build was failing somewhere
in the context of sudo, sudo-rs and pseudo :-)

For images that contain default users (like the new ubuntu ones) it is
helpful to add:

DOCKERFILE_APPEND="RUN userdel -r ubuntu"

diff --git a/dockerize b/dockerize
--- a/dockerize
+++ b/dockerize
@@ -66,9 +66,10 @@ else
 fi
 
 if ! getent passwd $(id -u) > /dev/null; then
-    /usr/sbin/useradd -u $(id -u) -g $(id -g) -m user$(id -u)
+    /usr/sbin/useradd -u $(id -u) -g $(id -g) -d $HOME -m user$(id -u)
 else
-    echo "User with id $(id -u) exists."
+    echo "User with id $(id -u) exists. This causes all kinds of issues. Abort."
+    exit 1
 fi
 
 sudo chmod a-s /usr/sbin/useradd && sudo chmod a-s /usr/sbin/groupadd
